### ISSUE TITLE
Check references to master

### ISSUE THREAD

**Issue by rowannekabalan** [guardian/tags-thrift-schema#31]
The master branch of this repository has been migrated to main using the [master-to-main](https://github.com/guardian/master-to-main) tool.

  Some files in the repository contain the word master. Please check the following files and update where required:

  - [x] [build.sbt](https://github.com/guardian/tags-thrift-schema/blob/main/build.sbt)

**Comment by ParisaTork** [comment]
Branch ref to master already updated by this commit: https://github.com/guardian/tags-thrift-schema/commit/264340311ff7d21c0d84e1f2972f58d8ed356bd8
